modLoader="javafml"
loaderVersion="[47,48)"
license="All Rights Reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="IGY_gaming"
description='''
Cinematic Hollow Purple effect for Forge 1.20.1.
Command: /purpure <player> [hits]
Designed for Stream To Earn console commands.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,48)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
